//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuHuong_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSach
    {
        public LoaiSach()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public string maLoai { get; set; }
        public string tenLoai { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
