//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string namSX { get; set; }
        public Nullable<double> GiaSP { get; set; }
        public string hinhAnh { get; set; }
        public string maLoai { get; set; }
    
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
